# Generated by Django 2.2.24 on 2021-09-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='yazan',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='olusturulma_zamani',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='yayin_zamani',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='icerik',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='baslık',
            new_name='title',
        ),
    ]
